functions:
  # Health Check
  - name: health-check
    handler: app.handler
    runtime: nodejs22.x
    timeout: 10
    memory_size: 128
    description: Health check endpoint
    api_path: /health
    http_method: GET
    source_path: ../../../../lambdas/handlers/health
    environment:
      SERVICE_NAME: screenshots-service
